### ISSUE TITLE
Not all values are tested

### ISSUE THREAD

**Issue by turalcar** [RunDevelopment/rounding-bench-rs#1]
It looks like the generator only tests values from 0u16 to 31u16 inclusive
https://github.com/RunDevelopment/rounding-bench-rs/blob/b66b6baeaf06043346232f2ff24bdcbdf985be47/benches/bench.rs#L30

**Comment by RunDevelopment** [comment]
Oh, that's an embarrassing mistake. When I started this, I used a synthetic benchmark that just tested the `u5_to_u8_*` functions directly without the pixel decoding code. Seems like I forgot to change this part of the benchmark... Thank you for reporting this! 

Luckily, this doesn't affect the results of any function except for `u5_to_u8_naive` on my machine. `u5_to_u8_naive` **doubled** its runtime on my machine from around 100µs to 200µs. My guess is that `f32::round` internally handles 0 separately. Previously, 2 out of 3 channels were always 0, so that likely explains the huge difference.

Anyway, I fixed the bug and updated the timings in the README. I'll also update the article shortly.
